[book]
title = "넷평의 Unity 노트"
description = "study.unity"
authors = ["netpyoung"]
language = "ko"
src = "src"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
additional-css = ["custom.css"]
no-section-label = true
site-url = "/study.unity/"
git-repository-url = "https://github.com/netpyoung/study.unity"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/netpyoung/study.unity/edit/main/{path}"
